### ISSUE TITLE
Send/Confirm screen - New field with the `Privacy` of the Transaction.

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#483]
I think is a good idea to include `Privacy` info in the confirm screen (sending). 

But there are several combinations to do this properly:
* from `orchard-sapling` (Zingo) -> to transparent -> `Privacy: Transparent or Public`?.
* from `orchard-sapling` (Zingo) -> to sapling -> `Privacy: Amounts Revealed`?.
* from `orchard-sapling` (Zingo) -> to orchard -> `Privacy: Shielded or Private`?.
* from `orchard-sapling` (Zingo) -> to UA (orchard, sapling & transparent receivers) -> `Privacy: Shielded or Private`?.
* from `orchard-sapling` (Zingo) -> to UA (orchard & sapling receivers) -> `Privacy: Shielded or Private`?.
* from `orchard-sapling` (Zingo) -> to UA (orchard & transparent receivers) -> `Privacy: Shielded or Private`?.
* from `orchard-sapling` (Zingo) -> to UA (orchard receiver) -> `Privacy: Shielded or Private`?.
* from `orchard-sapling` (Zingo) -> to UA (sapling & transparent receivers) -> `Privacy: Amounts Revealed`?.
* from `orchard-sapling` (Zingo) -> to UA (sapling receiver) -> `Privacy: Amounts Revealed`?.

I don't know if I'm missing something, @edicksonjga. Please feel free to add/fix anything.

@AloeareV @zancas please, take a look at this, your opinion is needed.

**Comment by Edicksonjga** [comment]
Depending on the type of transaction, the privacy information I believe may be as follows:

### Transaction Types:

1. **Private**

- _Orchard to Orchard._

Transaction where the sender has funds in Orchard and sends to the receiver via a unified address containing the Orchard pool.

- _Sapling to Sapling._

Transaction where the sender has funds in Sapling and sends to a receiver with Z address or unified address with Sapling receiver as the only shielded pool.

2. **Amount Revealed**

- _Orchard to Sapling._

Transaction where the sender has funds in Orchard and sends to a receiver with Z address or unified address with Sapling receiver as the only shielded pool. 

- _Sapling to Orchard._

Transaction where sender has funds in Sapling and sends to receiver with full unified address or Unified Address where Orchard is the only shielded pool.

- _Sapling+Orchard to Orchard or Sapling._

Sender has funds in Sapling and Orchard and sends a transaction that occupies both pools to the Sapling address or Unified address of any type.

3. **Deshielded**

- _Orchard to Transparent_

Send funds from Orchard to a transparent address.

- _Sapling to Transparent_

Send funds from Sapling to a transparent address.

With Zingo there are no Public transactions because there is no way to spend what you have in the transparent pool, first you have to Shield, but the Shielding process does not show that shipping confirmation screen, so there is no need for the **Shielded** label.

**Comment by juanky201271** [comment]
I'm missing one case:
* Sapling+Orchard to Transparent

I guess is: `Deshielded`?

**Comment by Edicksonjga** [comment]
> I'm missing one case:
> * Sapling+Orchard to Transparent
> 
> I guess is: `Deshielded`?

Yes 👍
