### ISSUE TITLE
Allow viewing the wallet seed without an internet connection

### ISSUE THREAD

**Issue by metalworker2** [zingolabs/zingo-mobile#548]
If Zingo does not have internet connection then the wallet will not open. The user will see a screen that says "Network Status (Internet) No Internet Connection" and cannot do anything else. This means that if the user does not have internet connection on their phone, they don't have any ability to even export their seed/private keys if they need to. This can be improved by allowing the user full access to the wallet, still with some error message about needing an internet connection, but provide access to wallet seed so user can take their wallet to another device if needed.

**Comment by juanky201271** [comment]
Thanks @metalworker2 
Honestly I think you are totally right, we need to change this allowing the user to use the App with no internet connection. The problem here is: The app needs to connect to a server in order to open the wallet file inside of the device...
@AloeareV What do you think about this? Do you think we can open the wallet file in the device with no internet, to allow the user to see all the info inside of the wallet file?

But I have to say that zingo don't store the seed in any place, so in order to view the seed you need internet connection yes or yes... FYI.

**Comment by juanky201271** [comment]
You need to access to the server in order to get the seed, with Wifi or Cellular Data, but you need internet connection. Closing this issue since it's a impossible case.

**Comment by metalworker2** [comment]
@juanky201271 the seed is stored locally on the phone, is it not? why do you say that internet connection is needed to view the seed?
