### ISSUE TITLE
Give option to download memos only over wifi

### ISSUE THREAD

**Issue by metalworker2** [zingolabs/zingo-mobile#550]
If the user wants full privacy _and_ full functionality, they must choose the option "all" under the "Memo Download" in Settings menu. But as the app says, this can use a lot of bandwidth. I propose a fourth mode of operation, in addition to current "none", "wallet", and "all" memo download options: "all, wifi-only". If this option is selected, then all memos will only be downloaded if the user is connected to wifi. Otherwise, the wallet will operate as if in 
none" mode. Once user connects to wifi, wallet will switch to operate as if in "all" mode and sync the memos that it has not synced yet. This will give the user max privacy without draining their bandwidth if they are on limited data cell plan. The user can always switch to "all" if they need all the memos and are willing to pay the bandwidth cost even when not on wifi.

**Comment by juanky201271** [comment]
Thanks @metalworker2.
Maybe I'm wrong, but I can see an issue with this new feature... Since the App itself can decide if download memos or not depending on WiFi availability, the result can be that some transactions have the memos and other haven't... this can be really confusing for the users.
Another thing to consider is: in this scenario with an intermittent Wifi the App will change this option in the blockchain wallet from `all` or `wallet` to `none` and vice versa `all` the time... I think this is not ideal.
The abstract idea is really good, but the possible implementation is not that good, IMO.
What do you think @edicksonjga?

**Comment by juanky201271** [comment]
We think the user have to have the last word about this. Some idea about the above reasons? @metalworker2

**Comment by juanky201271** [comment]
closing because it is not planing...
