### ISSUE TITLE
cannot deserialize b64 

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#634]
this is a bug that prevents users from opening their wallets.

i have tracked this down to the use of a deprecated function
https://docs.rs/base64/latest/base64/fn.encode.html

**Comment by juanky201271** [comment]
We are using both deprecated functions (encode & decode) using the STANDARD engine. Any idea to change/fix this keeping backwards compatibility. We can use `Engine::encode/decode` instead, sorry, but this is out of my scope... @fluidvanadium

**Comment by juanky201271** [comment]
digging a little bit it seems like you can migrate:

use base64::{decode, encode}
decode(&base64_data)

to:

use base64::{engine::general_purpose::STANDARD}
STANDARD.decode(&base64_data)

@AloeareV @zancas @Oscar-Pepper @fluidvanadium what do you think?

PS: IMO I don't think we will solve this bug with this migration since base64::decode/encode is a high level function using the same code underneath from the Standard Engine.

**Comment by zancas** [comment]
Is this operation specific to `iOS`?   Are we using different Rust codecs for `iOS` and `Android`?

**Comment by juanky201271** [comment]
> Is this operation specific to `iOS`? Are we using different Rust codecs for `iOS` and `Android`?

We have only one layer of rust (uniffi) for both Platforms.

**Comment by juanky201271** [comment]
![Image-1(1)](https://github.com/zingolabs/zingo-mobile/assets/43755989/97aeab6e-84cf-4184-810f-9238c9b1e767)
